services:
  app:
    image: nguyenphuc4444/vngo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
      - JWT_VALID_DURATION=3600
      - JWT_REFRESHABLE_DURATION=86400