server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/vngo"
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/vngo}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME:root} 
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${JWT_SIGNER_KEY:dev_jwt_secret_key}
  valid-duration: "3600"
  refreshable-duration: "86400"
