server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/vngo"
spring:
  datasource:
    url: ${DB_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME} 
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: "3600"
  refreshable-duration: "86400"
